spring:
  profiles:
    active: prod
  datasource:
    readSize: 1
    # 使用druid数据源sendCustomerTextMessage
    type: com.alibaba.druid.pool.DruidDataSource
    url: ${databaseconfig.datasource.url}
    username: ${databaseconfig.datasource.username}
    password: ${databaseconfig.datasource.password}
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: true
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
logging:
  config: classpath:log/${spring.profiles.active}/logback.xml
server:
  port: ${application.port}
  servlet:
    context-path: ${application.context-path}
